In [2]:
import numpy as np

In [18]:
A2 = [
    [-4, 1, -7],
    [1, 9, 1],
    [-7, 1, 7]
    ]
eps = 0.01

In [19]:
#Поиск максимального ВНЕ главной диагонали элементов
def max_no_diag(A):
    row = len(A)
    col = len(A[0])
    i_max = 0
    j_max = 1
    result = abs(A[i_max][j_max])
    
    for i in range(row):
        for j in range(col):
            if i != j and abs(A[i][j]) > result:
                result = abs(A[i][j])
                i_max = i
                j_max = j
    
    return (i_max, j_max)

#Нахождения матрицы А для следующей итерации
def A_iter(A_arg, eps):
    
    A = np.array(A_arg)
    row = len(A)
    col = len(A[0])
    
    counter = 0
    flag = True
    while flag:
        
        counter += 1
        print("+++ Итерация:",counter, "+++")
        
        i, j = max_no_diag(A)
        print("Макс.элемент A[" + str(i) + "][" + str(j) + "]:", A[i][j])
        
        fi = 0.5 * np.arctan( 2.0 * A[i][j] / ( A[i][i] - A[j][j]) )
        
        U = np.eye(3)
        U[i][j] = -1 * np.sin(fi)
        U[j][i] = np.sin(fi)
        U[i][i] = np.cos(fi)
        U[j][j] = np.cos(fi)
        
        A = np.matmul(np.matmul(U.T, A), U)
        flag = abs(A[i][j]) > eps
        print("U.T * A * U :\n",A)
        print("Макс.элемент A[" + str(i) + "][" + str(j) + "]:", A[i][j])
        
    
    return A

In [20]:
#Условие остановки
def smallness_condition(A, eps):
    row = len(A)
    col = len(A[0])
    result = 0
    for i in range(row):
        for j in range(col):
            if i != j:
                result += A[i][j] ** 2
    
    return np.sqrt(result) > eps

#Метод Якоби
def Jacobi(A_arg, eps):
    A = np.array(A_arg)
    counter = 0 
    while smallness_condition(A, eps):
        counter += 1
        A = A_iter(A, eps)
    print("Количество итераций во внешнем цикле:", counter)
    return A.round(10)

In [21]:
def move_max(m,col):
    max_element = m[col][col]
    row = col
    #  по столбцу ниже диагонали
    for i in range(col + 1, len(m)):
        if abs(m[i][col]) > abs(max_element):
            max_element = m[i][col]
            row = i
    #если максимум не на диагонали
    if row != col:
        m[col], m[row] = m[row], m[col]
        
        
def gauss(m):
    n = len(m)
    # прямой ход
    #для всех столбцов
    for k in range(n - 1):
        # для каждого столбца перемещаем вверх максимум
        move_max(m, k)
        # по строке
        for i in range(k + 1, n):
            div = m[i][k] / m[k][k]
            m[i][-1] -= div * m[k][-1]
            for j in range(k, n):
                m[i][j] -= div * m[k][j]

    # вектор переменных            
    x = [0 for i in range(n)]    
    
    # обратный ход
    # снизу вверх
    x[n-1]=1
    for k in range(n - 2, -1, -1):
        x[k] = (m[k][-1] - sum([m[k][j] * x[j] for j in range(k + 1, n)])) / m[k][k]

    return x 

In [22]:
#Вызов метода Якоби для матрицы A
A = A2
lambdas = Jacobi(A, eps)
lambdas = np.diag(lambdas) #Вектор из собственных значений
for l in lambdas:
    print('Собственное число:', l)

+++ Итерация: 1 +++
Макс.элемент A[0][2]: -7
U.T * A * U :
 [[-7.40224691e+00  1.33653221e+00  3.69805442e-16]
 [ 1.33653221e+00  9.00000000e+00  4.62257138e-01]
 [ 6.49879647e-16  4.62257138e-01  1.04022469e+01]]
Макс.элемент A[0][2]: 3.6980544170153523e-16
+++ Итерация: 1 +++
Макс.элемент A[0][1]: 1.336532206429169
U.T * A * U :
 [[-7.51044017  0.         -0.03729805]
 [ 0.          9.10819326  0.46074995]
 [-0.03729805  0.46074995 10.40224691]]
Макс.элемент A[0][1]: 0.0
+++ Итерация: 1 +++
Макс.элемент A[1][2]: 0.4607499506040387
U.T * A * U :
 [[-7.51044017e+00  1.13568282e-02 -3.55269848e-02]
 [ 1.13568282e-02  8.96090640e+00  3.15221166e-17]
 [-3.55269848e-02  7.21559715e-17  1.05495338e+01]]
Макс.элемент A[1][2]: 3.152211655806811e-17
+++ Итерация: 1 +++
Макс.элемент A[0][2]: -0.035526984808461
U.T * A * U :
 [[-7.51051005e+00  1.13568062e-02 -1.50106853e-18]
 [ 1.13568062e-02  8.96090640e+00 -2.23406480e-05]
 [ 2.60676047e-16 -2.23406480e-05  1.05496037e+01]]
Макс.элемент A[0][

In [23]:
#Проверка собственных значений
A = np.array(A)
for l in lambdas:
    print('Собственное число:', l)
    print('Проверка:', abs( np.linalg.det( A - l * np.eye(3) ) ) <= eps ) #|A-lE| <= eps

Собственное число: -7.5105178846
Проверка: True
Собственное число: 8.9609142303
Проверка: True
Собственное число: 10.5496036542
Проверка: True


In [24]:
#Поиск собственных векторов
Xs = []
for l in lambdas:
    print('Собственное число:', l)
    A_tmp = np.append(A - l * np.eye(3), [[0],[0],[0]], axis = 1)
    X_tmp = gauss(A_tmp)
    Xs.append(X_tmp)
    print('Собственный вектор:', X_tmp, '\n')

Собственное число: -7.5105178846
Собственный вектор: [2.0465706943156787, -0.18452302439024842, 1] 

Собственное число: 8.9609142303
Собственный вектор: [-0.8453545169440214, -3.9565673883081494, 1] 

Собственное число: 10.5496036542
Собственный вектор: [-0.45703013076753374, 0.35039273930518733, 1] 



In [25]:
for v, l in zip(Xs, lambdas):
    v = np.array(v)
    left   = np.matmul(A, v)
    right  = np.array(v * l)
    print(left)
    print(right)
    print('Проверка:', np.allclose(left, right)) #Ax = lx
    print('\n')

[-15.3708058    1.38586347  -7.51051788]
[-15.3708058    1.38586347  -7.51051788]
Проверка: True


[ -7.57514932 -35.45446101   8.96091423]
[ -7.57514932 -35.45446101   8.96091423]
Проверка: True


[-4.82148674  3.69650452 10.54960365]
[-4.82148674  3.69650452 10.54960365]
Проверка: True


